// This file is automatically generated by a script based on the CommandBuilder API.
// This file adds additional overloads to the CommandBuilder API with convenience parameters like colors and durations.
using Unity.Burst;
using UnityEngine;
using System.Collections.Generic;
using Unity.Collections;
using Unity.Mathematics;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Jobs;

namespace Drawing {
	public partial struct CommandBuilder {
		/// <summary>\copydoc Line(float3,float3)</summary>
		public void Line (float3 a, float3 b, Color color) {
			Reserve<Color32, LineData>();
			Add(Command.Line | Command.PushColorInline);
			Add((Color32)color);
			Add(new LineData { a = a, b = b });
		}

		/// <summary>\copydoc Ray(float3,float3)</summary>
		public void Ray (float3 origin, float3 direction, Color color) {
			Line(origin, origin + direction, color);
		}

		/// <summary>\copydoc Ray(Ray,float)</summary>
		public void Ray (Ray ray, float length, Color color) {
			Line(ray.origin, ray.origin + ray.direction * length, color);
		}

		/// <summary>\copydoc Arc(float3,float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void Arc (float3 center, float3 start, float3 end, Color color) {
			PushColor(color);
			var d1 = start - center;
			var d2 = end - center;
			var normal = math.cross(d2, d1);

			if (math.any(normal != 0)) {
				var m = Matrix4x4.TRS(center, Quaternion.LookRotation(d1, normal), Vector3.one);
				var angle = Vector3.SignedAngle(d1, d2, normal) * Mathf.Deg2Rad;
				PushMatrix(m);
				CircleXZ(float3.zero, math.length(d1), 90 * Mathf.Deg2Rad, 90 * Mathf.Deg2Rad - angle);
				PopMatrix();
			}
			PopColor();
		}
		/// <summary>\copydoc CircleXZ(float3,float,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void CircleXZ (float3 center, float radius, float startAngle, float endAngle, Color color) {
			Reserve<Color32, CircleXZData>();
			Add(Command.CircleXZ | Command.PushColorInline);
			Add((Color32)color);
			Add(new CircleXZData { center = center, radius = radius, startAngle = startAngle, endAngle = endAngle });
		}

		/// <summary>\copydoc CircleXZ(float3,float,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void CircleXZ (float3 center, float radius, Color color) {
			CircleXZ(center, radius, 0f, 2 * Mathf.PI, color);
		}

		/// <summary>\copydoc CircleXY(float3,float,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void CircleXY (float3 center, float radius, float startAngle, float endAngle, Color color) {
			PushColor(color);
			PushMatrix(XZtoXYPlaneMatrix);
			CircleXZ(new float3(center.x, -center.z, center.y), radius, startAngle, endAngle);
			PopMatrix();
			PopColor();
		}
		/// <summary>\copydoc CircleXY(float3,float,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void CircleXY (float3 center, float radius, Color color) {
			CircleXY(center, radius, 0f, 2 * Mathf.PI, color);
		}
		/// <summary>\copydoc Circle(float3,float3,float)</summary>
		public void Circle (float3 center, float3 normal, float radius, Color color) {
			Reserve<Color32, CircleData>();
			Add(Command.Circle | Command.PushColorInline);
			Add((Color32)color);
			Add(new CircleData { center = center, normal = normal, radius = radius });
		}
		/// <summary>\copydoc WireCylinder(float3,float3,float)</summary>
		public void WireCylinder (float3 bottom, float3 top, float radius, Color color) {
			WireCylinder(bottom, top - bottom, math.length(top - bottom), radius, color);
		}

		/// <summary>\copydoc WireCylinder(float3,float3,float,float)</summary>
		public void WireCylinder (float3 position, float3 up, float height, float radius, Color color) {
			PushColor(color);
			var tangent = math.normalizesafe(math.cross(up, new float3(1, 1, 1)));

			// Note: second parameter is normalized (-1,1,1)
			if (math.all(tangent == float3.zero)) tangent = math.cross(up, new float3(-0.577350269f, 0.577350269f, 0.577350269f));

			using (WithMatrix(Matrix4x4.TRS(position, Quaternion.LookRotation(tangent, up), new Vector3(radius, height, radius)))) {
				CircleXZ(float3.zero, 1);
				if (height > 0) {
					CircleXZ(new float3(0, 1, 0), 1);
					Line(new float3(1, 0, 0), new float3(1, 1, 0));
					Line(new float3(-1, 0, 0), new float3(-1, 1, 0));
					Line(new float3(0, 0, 1), new float3(0, 1, 1));
					Line(new float3(0, 0, -1), new float3(0, 1, -1));
				}
			}
			PopColor();
		}

		/// <summary>\copydoc WireCapsule(float3,float3,float)</summary>
		public void WireCapsule (float3 bottom, float3 top, float radius, Color color) {
			WireCapsule(bottom, top - bottom, math.length(top - bottom), radius, color);
		}
		/// <summary>\copydoc WireCapsule(float3,float3,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void WireCapsule (float3 position, float3 up, float height, float radius, Color color) {
			PushColor(color);
			up = math.normalizesafe(up);
			// Note; second parameter is normalized (1,1,1)
			var tangent = math.cross(up, new float3(0.577350269f, 0.577350269f, 0.577350269f));

			// Note: second parameter is normalized (-1,1,1)
			if (math.all(tangent == float3.zero)) tangent = math.cross(up, new float3(-0.577350269f, 0.577350269f, 0.577350269f));

			height = math.max(height, radius*2);

			using (WithMatrix(Matrix4x4.TRS(position, Quaternion.LookRotation(tangent, up), Vector3.one))) {
				CircleXZ(new float3(0, radius, 0), radius);
				CircleXY(new float3(0, radius, 0), radius, Mathf.PI, 2 * Mathf.PI);
				PushMatrix(XZtoYZPlaneMatrix);
				CircleXZ(new float3(radius, 0, 0), radius, Mathf.PI*0.5f, Mathf.PI*1.5f);
				PopMatrix();
				if (height > 0) {
					var upperY = height - radius;
					var lowerY = radius;
					CircleXZ(new float3(0, upperY, 0), radius);
					CircleXY(new float3(0, upperY, 0), radius, 0, Mathf.PI);
					PushMatrix(XZtoYZPlaneMatrix);
					CircleXZ(new float3(upperY, 0, 0), radius, -Mathf.PI*0.5f, Mathf.PI*0.5f);
					PopMatrix();
					Line(new float3(radius, lowerY, 0), new float3(radius, upperY, 0));
					Line(new float3(-radius, lowerY, 0), new float3(-radius, upperY, 0));
					Line(new float3(0, lowerY, radius), new float3(0, upperY, radius));
					Line(new float3(0, lowerY, -radius), new float3(0, upperY, -radius));
				}
			}
			PopColor();
		}
		/// <summary>\copydoc WireSphere(float3,float)</summary>
		public void WireSphere (float3 position, float radius, Color color) {
			PushColor(color);
			Circle(position, new float3(1, 0, 0), radius);
			Circle(position, new float3(0, 1, 0), radius);
			Circle(position, new float3(0, 0, 1), radius);
			PopColor();
		}
		/// <summary>\copydoc Polyline(List<Vector3>,bool)</summary>
		/// <param name="color">Color of the object</param>
		[BurstDiscard]
		public void Polyline (List<Vector3> points, bool cycle, Color color) {
			PushColor(color);
			for (int i = 0; i < points.Count - 1; i++) {
				Line(points[i], points[i+1]);
			}
			if (cycle && points.Count > 1) Line(points[points.Count - 1], points[0]);
			PopColor();
		}

		/// <summary>\copydoc Polyline(List<Vector3>,bool)</summary>
		/// <param name="color">Color of the object</param>
		[BurstDiscard]
		public void Polyline (List<Vector3> points, Color color) {
			Polyline(points, false, color);
		}

		/// <summary>\copydoc Polyline(Vector3[],bool)</summary>
		/// <param name="color">Color of the object</param>
		[BurstDiscard]
		public void Polyline (Vector3[] points, bool cycle, Color color) {
			PushColor(color);
			for (int i = 0; i < points.Length - 1; i++) {
				Line(points[i], points[i+1]);
			}
			if (cycle && points.Length > 1) Line(points[points.Length - 1], points[0]);
			PopColor();
		}

		/// <summary>\copydoc Polyline(Vector3[],bool)</summary>
		/// <param name="color">Color of the object</param>
		[BurstDiscard]
		public void Polyline (Vector3[] points, Color color) {
			Polyline(points, false, color);
		}

		/// <summary>\copydoc Polyline(float3[],bool)</summary>
		/// <param name="color">Color of the object</param>
		[BurstDiscard]
		public void Polyline (float3[] points, bool cycle, Color color) {
			PushColor(color);
			for (int i = 0; i < points.Length - 1; i++) {
				Line(points[i], points[i+1]);
			}
			if (cycle && points.Length > 1) Line(points[points.Length - 1], points[0]);
			PopColor();
		}

		/// <summary>\copydoc Polyline(float3[],bool)</summary>
		/// <param name="color">Color of the object</param>
		[BurstDiscard]
		public void Polyline (float3[] points, Color color) {
			Polyline(points, false, color);
		}

		/// <summary>\copydoc Polyline(NativeArray<float3>,bool)</summary>
		/// <param name="color">Color of the object</param>
		public void Polyline (NativeArray<float3> points, bool cycle, Color color) {
			PushColor(color);
			for (int i = 0; i < points.Length - 1; i++) {
				Line(points[i], points[i+1]);
			}
			if (cycle && points.Length > 1) Line(points[points.Length - 1], points[0]);
			PopColor();
		}

		/// <summary>\copydoc Polyline(NativeArray<float3>,bool)</summary>
		/// <param name="color">Color of the object</param>
		public void Polyline (NativeArray<float3> points, Color color) {
			Polyline(points, false, color);
		}

		/// <summary>\copydoc WireBox(float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void WireBox (float3 center, float3 size, Color color) {
			WireBox(new Bounds(center, size), color);
		}

		/// <summary>\copydoc WireBox(float3,Quaternion,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void WireBox (float3 center, Quaternion rotation, float3 size, Color color) {
			PushColor(color);
			using (WithMatrix(Matrix4x4.TRS(center, rotation, size))) {
				WireBox(new Bounds(new Vector3(0.5f, 0.5f, 0.5f), Vector3.one));
			}
			PopColor();
		}

		/// <summary>\copydoc WireBox(Bounds)</summary>
		public void WireBox (Bounds bounds, Color color) {
			PushColor(color);
			var min = bounds.min;
			var max = bounds.max;

			Line(new float3(min.x, min.y, min.z), new float3(max.x, min.y, min.z));
			Line(new float3(max.x, min.y, min.z), new float3(max.x, min.y, max.z));
			Line(new float3(max.x, min.y, max.z), new float3(min.x, min.y, max.z));
			Line(new float3(min.x, min.y, max.z), new float3(min.x, min.y, min.z));

			Line(new float3(min.x, max.y, min.z), new float3(max.x, max.y, min.z));
			Line(new float3(max.x, max.y, min.z), new float3(max.x, max.y, max.z));
			Line(new float3(max.x, max.y, max.z), new float3(min.x, max.y, max.z));
			Line(new float3(min.x, max.y, max.z), new float3(min.x, max.y, min.z));

			Line(new float3(min.x, min.y, min.z), new float3(min.x, max.y, min.z));
			Line(new float3(max.x, min.y, min.z), new float3(max.x, max.y, min.z));
			Line(new float3(max.x, min.y, max.z), new float3(max.x, max.y, max.z));
			Line(new float3(min.x, min.y, max.z), new float3(min.x, max.y, max.z));
			PopColor();
		}

		/// <summary>\copydoc WireMesh(Mesh)</summary>
		public void WireMesh (Mesh mesh, Color color) {
			PushColor(color);
#if UNITY_2020_1_OR_NEWER
			// Use a burst compiled function to draw the lines
			// This is significantly faster than pure C# (about 5x).
			var meshDataArray = Mesh.AcquireReadOnlyMeshData(mesh);
			var meshData = meshDataArray[0];

			JobWireMesh.JobWireMeshFunctionPointer(ref meshData, ref this);
			meshDataArray.Dispose();
#else
			Debug.LogError("The WireMesh method is only suppored in Unity 2020.1 or later");
#endif
			PopColor();
		}
		/// <summary>\copydoc SolidMesh(Mesh)</summary>
		public void SolidMesh (Mesh mesh, Color color) {
			PushColor(color);
			var g = gizmos.Target as DrawingData;

			g.data.Get(uniqueID).meshes.Add(mesh);
			PopColor();
		}
		/// <summary>\copydoc Cross(float3,float)</summary>
		public void Cross (float3 position, float size, Color color) {
			PushColor(color);
			size *= 0.5f;
			Line(position - new float3(size, 0, 0), position + new float3(size, 0, 0));
			Line(position - new float3(0, size, 0), position + new float3(0, size, 0));
			Line(position - new float3(0, 0, size), position + new float3(0, 0, size));
			PopColor();
		}
		/// <summary>\copydoc Cross(float3,float)</summary>
		public void Cross (float3 position, Color color) {
			Cross(position, 1, color);
		}
		/// <summary>\copydoc CrossXZ(float3,float)</summary>
		public void CrossXZ (float3 position, float size, Color color) {
			PushColor(color);
			size *= 0.5f;
			Line(position - new float3(size, 0, 0), position + new float3(size, 0, 0));
			Line(position - new float3(0, 0, size), position + new float3(0, 0, size));
			PopColor();
		}

		/// <summary>\copydoc CrossXZ(float3,float)</summary>
		public void CrossXZ (float3 position, Color color) {
			CrossXZ(position, 1, color);
		}

		/// <summary>\copydoc CrossXY(float3,float)</summary>
		public void CrossXY (float3 position, float size, Color color) {
			PushColor(color);
			size *= 0.5f;
			Line(position - new float3(size, 0, 0), position + new float3(size, 0, 0));
			Line(position - new float3(0, size, 0), position + new float3(0, size, 0));
			PopColor();
		}
		/// <summary>\copydoc CrossXY(float3,float)</summary>
		public void CrossXY (float3 position, Color color) {
			CrossXY(position, 1, color);
		}
		/// <summary>\copydoc Bezier(float3,float3,float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void Bezier (float3 p0, float3 p1, float3 p2, float3 p3, Color color) {
			PushColor(color);
			float3 prev = p0;

			for (int i = 1; i <= 20; i++) {
				float t = i/20.0f;
				float3 p = EvaluateCubicBezier(p0, p1, p2, p3, t);
				Line(prev, p);
				prev = p;
			}
			PopColor();
		}
		/// <summary>\copydoc CatmullRom(List<Vector3>)</summary>
		/// <param name="color">Color of the object</param>
		public void CatmullRom (List<Vector3> points, Color color) {
			if (points.Count < 2) return;
			PushColor(color);

			if (points.Count == 2) {
				Line(points[0], points[1]);
			} else {
				// count >= 3
				var count = points.Count;
				// Draw first curve, this is special because the first two control points are the same
				CatmullRom(points[0], points[0], points[1], points[2]);
				for (int i = 0; i + 3 < count; i++) {
					CatmullRom(points[i], points[i+1], points[i+2], points[i+3]);
				}
				// Draw last curve
				CatmullRom(points[count-3], points[count-2], points[count-1], points[count-1]);
			}
			PopColor();
		}
		/// <summary>\copydoc CatmullRom(float3,float3,float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void CatmullRom (float3 p0, float3 p1, float3 p2, float3 p3, Color color) {
			PushColor(color);
			// References used:
			// p.266 GemsV1
			//
			// tension is often set to 0.5 but you can use any reasonable value:
			// http://www.cs.cmu.edu/~462/projects/assn2/assn2/catmullRom.pdf
			//
			// bias and tension controls:
			// http://local.wasp.uwa.edu.au/~pbourke/miscellaneous/interpolation/

			// We will convert the catmull rom spline to a bezier curve for simplicity.
			// The end result of this will be a conversion matrix where we transform catmull rom control points
			// into the equivalent bezier curve control points.

			// Conversion matrix
			// =================

			// A centripetal catmull rom spline can be separated into the following terms:
			// 1 * p1 +
			// t * (-0.5 * p0 + 0.5*p2) +
			// t*t * (p0 - 2.5*p1  + 2.0*p2 + 0.5*t2) +
			// t*t*t * (-0.5*p0 + 1.5*p1 - 1.5*p2 + 0.5*p3)
			//
			// Matrix form:
			// 1     t   t^2 t^3
			// {0, -1/2, 1, -1/2}
			// {1, 0, -5/2, 3/2}
			// {0, 1/2, 2, -3/2}
			// {0, 0, -1/2, 1/2}

			// Transposed matrix:
			// M_1 = {{0, 1, 0, 0}, {-1/2, 0, 1/2, 0}, {1, -5/2, 2, -1/2}, {-1/2, 3/2, -3/2, 1/2}}

			// A bezier spline can be separated into the following terms:
			// (-t^3 + 3 t^2 - 3 t + 1) * c0 +
			// (3t^3 - 6*t^2 + 3t) * c1 +
			// (3t^2 - 3t^3) * c2 +
			// t^3 * c3
			//
			// Matrix form:
			// 1  t  t^2  t^3
			// {1, -3, 3, -1}
			// {0, 3, -6, 3}
			// {0, 0, 3, -3}
			// {0, 0, 0, 1}

			// Transposed matrix:
			// M_2 = {{1, 0, 0, 0}, {-3, 3, 0, 0}, {3, -6, 3, 0}, {-1, 3, -3, 1}}

			// Thus a bezier curve can be evaluated using the expression
			// output1 = T * M_1 * c
			// where T = [1, t, t^2, t^3] and c being the control points c = [c0, c1, c2, c3]^T
			//
			// and a catmull rom spline can be evaluated using
			//
			// output2 = T * M_2 * p
			// where T = same as before and p = [p0, p1, p2, p3]^T
			//
			// We can solve for c in output1 = output2
			// T * M_1 * c = T * M_2 * p
			// M_1 * c = M_2 * p
			// c = M_1^(-1) * M_2 * p
			// Thus a conversion matrix from p to c is M_1^(-1) * M_2
			// This can be calculated and the result is the following matrix:
			//
			// {0, 1, 0, 0}
			// {-1/6, 1, 1/6, 0}
			// {0, 1/6, 1, -1/6}
			// {0, 0, 1, 0}
			// ------------------------------------------------------------------
			//
			// Using this we can calculate c = M_1^(-1) * M_2 * p
			var c0 = p1;
			var c1 = (-p0 + 6*p1 + 1*p2)*(1/6.0f);
			var c2 = (p1 + 6*p2 - p3)*(1/6.0f);
			var c3 = p2;

			// And finally draw the bezier curve which is equivalent to the desired catmull-rom spline
			Bezier(c0, c1, c2, c3);
			PopColor();
		}
		/// <summary>\copydoc Arrow(float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void Arrow (float3 from, float3 to, Color color) {
			ArrowRelativeSizeHead(from, to, new float3(0, 1, 0), 0.2f, color);
		}
		/// <summary>\copydoc Arrow(float3,float3,float3,float)</summary>
		/// <param name="color">Color of the object</param>
		public void Arrow (float3 from, float3 to, float3 up, float headSize, Color color) {
			PushColor(color);
			var length_sq = math.lengthsq(to - from);

			if (length_sq > 0.000001f) {
				ArrowRelativeSizeHead(from, to, up, headSize * math.rsqrt(length_sq));
			}
			PopColor();
		}
		/// <summary>\copydoc ArrowRelativeSizeHead(float3,float3,float3,float)</summary>
		/// <param name="color">Color of the object</param>
		public void ArrowRelativeSizeHead (float3 from, float3 to, float3 up, float headFraction, Color color) {
			PushColor(color);
			Line(from, to);
			var dir = to - from;

			var normal = math.cross(dir, up);
			// Pick a different up direction if the direction happened to be colinear with that one.
			if (math.all(normal == 0)) normal = math.cross(new float3(1, 0, 0), dir);
			// Pick a different up direction if up=(1,0,0) and thus the above check would have generated a zero vector again
			if (math.all(normal == 0)) normal = math.cross(new float3(0, 1, 0), dir);

			Line(to, to - (dir + normal) * headFraction);
			Line(to, to - (dir - normal) * headFraction);
			PopColor();
		}
		/// <summary>\copydoc Arrowhead(float3,float3,float)</summary>
		/// <param name="color">Color of the object</param>
		public void Arrowhead (float3 center, float3 direction, float radius, Color color) {
			Arrowhead(center, direction, new float3(0, 1, 0), radius, color);
		}
		/// <summary>\copydoc Arrowhead(float3,float3,float3,float)</summary>
		/// <param name="color">Color of the object</param>
		public void Arrowhead (float3 center, float3 direction, float3 up, float radius, Color color) {
			if (math.all(direction == 0)) return;
			PushColor(color);
			direction = math.normalizesafe(direction);
			var normal = math.cross(direction, up);
			const float SinPiOver3 = 0.866025f;
			const float CosPiOver3 = 0.5f;
			var circleCenter = center - radius * (1 - CosPiOver3)*0.5f * direction;
			var p1 = circleCenter + radius * direction;
			var p2 = circleCenter - radius * CosPiOver3 * direction + radius * SinPiOver3 * normal;
			var p3 = circleCenter - radius * CosPiOver3 * direction - radius * SinPiOver3 * normal;
			Line(p1, p2);
			Line(p2, circleCenter);
			Line(circleCenter, p3);
			Line(p3, p1);
			PopColor();
		}
		/// <summary>\copydoc ArrowheadArc(float3,float3,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void ArrowheadArc (float3 origin, float3 direction, float offset, float width, Color color) {
			if (!math.any(direction)) return;
			if (offset < 0) throw new System.ArgumentOutOfRangeException(nameof(offset));
			if (offset == 0) return;
			PushColor(color);

			var up = new Vector3(0, 1, 0);
			var rot = Quaternion.LookRotation(direction, up);
			PushMatrix(Matrix4x4.TRS(origin, rot, Vector3.one));
			var a1 = math.PI * 0.5f - width * (0.5f * Mathf.Deg2Rad);
			var a2 = math.PI * 0.5f + width * (0.5f * Mathf.Deg2Rad);
			CircleXZ(float3.zero, offset, a1, a2);
			var p1 = new float3(math.cos(a1), 0, math.sin(a1)) * offset;
			var p2 = new float3(math.cos(a2), 0, math.sin(a2)) * offset;
			const float sqrt2 = 1.4142f;
			var p3 = new float3(0, 0, sqrt2 * offset);
			Line(p1, p3);
			Line(p2, p3);
			PopMatrix();
			PopColor();
		}
		/// <summary>\copydoc ArrowheadArc(float3,float3,float,float)</summary>
		/// <param name="color">Color of the object</param>
		public void ArrowheadArc (float3 origin, float3 direction, float offset, Color color) {
			ArrowheadArc(origin, direction, offset, 60, color);
		}
		/// <summary>\copydoc WireGrid(float3,Quaternion,int2,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void WireGrid (float3 center, Quaternion rotation, int2 cells, float2 totalSize, Color color) {
			PushColor(color);
			cells = math.max(cells, new int2(1, 1));
			PushMatrix(Matrix4x4.TRS(center, rotation, new Vector3(totalSize.x, 0, totalSize.y)));
			int w = cells.x;
			int h = cells.y;
			for (int i = 0; i <= w; i++) Line(new float3(i/(float)w - 0.5f, 0, -0.5f), new float3(i/(float)w - 0.5f, 0, 0.5f));
			for (int i = 0; i <= h; i++) Line(new float3(-0.5f, 0, i/(float)h - 0.5f), new float3(0.5f, 0, i/(float)h - 0.5f));
			PopMatrix();
			PopColor();
		}

		/// <summary>\copydoc WireTriangle(float3,float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void WireTriangle (float3 a, float3 b, float3 c, Color color) {
			PushColor(color);
			Line(a, b);
			Line(b, c);
			Line(c, a);
			PopColor();
		}
		/// <summary>\copydoc WireRectangleXZ(float3,float2)</summary>
		public void WireRectangleXZ (float3 center, float2 size, Color color) {
			WireRectangle(center, Quaternion.identity, size, color);
		}
		/// <summary>\copydoc WireRectangle(float3,Quaternion,float2)</summary>
		public void WireRectangle (float3 center, Quaternion rotation, float2 size, Color color) {
			WirePlane(center, rotation, size, color);
		}
		/// <summary>\copydoc WireRectangle(Rect)</summary>
		public void WireRectangle (Rect rect, Color color) {
			PushColor(color);
			float2 min = rect.min;
			float2 max = rect.max;

			Line(new float3(min.x, min.y, 0), new float3(max.x, min.y, 0));
			Line(new float3(max.x, min.y, 0), new float3(max.x, max.y, 0));
			Line(new float3(max.x, max.y, 0), new float3(min.x, max.y, 0));
			Line(new float3(min.x, max.y, 0), new float3(min.x, min.y, 0));
			PopColor();
		}
		/// <summary>\copydoc WireTriangle(float3,Quaternion,float)</summary>
		/// <param name="color">Color of the object</param>
		public void WireTriangle (float3 center, Quaternion rotation, float radius, Color color) {
			WirePolygon(center, 3, rotation, radius, color);
		}
		/// <summary>\copydoc WirePentagon(float3,Quaternion,float)</summary>
		/// <param name="color">Color of the object</param>
		public void WirePentagon (float3 center, Quaternion rotation, float radius, Color color) {
			WirePolygon(center, 5, rotation, radius, color);
		}
		/// <summary>\copydoc WireHexagon(float3,Quaternion,float)</summary>
		/// <param name="color">Color of the object</param>
		public void WireHexagon (float3 center, Quaternion rotation, float radius, Color color) {
			WirePolygon(center, 6, rotation, radius, color);
		}
		/// <summary>\copydoc WirePolygon(float3,int,Quaternion,float)</summary>
		/// <param name="color">Color of the object</param>
		public void WirePolygon (float3 center, int vertices, Quaternion rotation, float radius, Color color) {
			PushColor(color);
			PushMatrix(Matrix4x4.TRS(center, rotation, Vector3.one * radius));
			float3 prev = new float3(0, 0, 1);
			for (int i = 1; i <= vertices; i++) {
				float a = 2 * math.PI * (i / (float)vertices);
				var p = new float3(math.sin(a), 0, math.cos(a));
				Line(prev, p);
				prev = p;
			}
			PopMatrix();
			PopColor();
		}
		/// <summary>\copydoc SolidPlane(float3,float3,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void SolidPlane (float3 center, float3 normal, float2 size, Color color) {
			SolidPlane(center, Quaternion.LookRotation(calculateTangent(normal)), size, color);
		}
		/// <summary>\copydoc SolidPlane(float3,Quaternion,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void SolidPlane (float3 center, Quaternion rotation, float2 size, Color color) {
			PushMatrix(Matrix4x4.Rotate(rotation));
			Reserve<Color32, BoxData>();
			Add(Command.Box | Command.PushColorInline);
			Add((Color32)color);
			Add(new BoxData { center = center, size = new float3(size.x, 0, size.y) });
			PopMatrix();
		}
		/// <summary>\copydoc WirePlane(float3,float3,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void WirePlane (float3 center, float3 normal, float2 size, Color color) {
			WirePlane(center, Quaternion.LookRotation(calculateTangent(normal)), size, color);
		}
		/// <summary>\copydoc WirePlane(float3,Quaternion,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void WirePlane (float3 center, Quaternion rotation, float2 size, Color color) {
			PushColor(color);
			PushMatrix(Matrix4x4.TRS(center, rotation, new Vector3(0.5f * size.x, 0, 0.5f * size.y)));
			Line(new float3(-1, 0, -1), new float3(1, 0, -1));
			Line(new float3(1, 0, -1), new float3(1, 0, 1));
			Line(new float3(1, 0, 1), new float3(-1, 0, 1));
			Line(new float3(-1, 0, 1), new float3(-1, 0, -1));
			PopMatrix();
			PopColor();
		}
		/// <summary>\copydoc PlaneWithNormal(float3,float3,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void PlaneWithNormal (float3 center, float3 normal, float2 size, Color color) {
			PlaneWithNormal(center, Quaternion.LookRotation(calculateTangent(normal)), size, color);
		}
		/// <summary>\copydoc PlaneWithNormal(float3,Quaternion,float2)</summary>
		/// <param name="color">Color of the object</param>
		public void PlaneWithNormal (float3 center, Quaternion rotation, float2 size, Color color) {
			PushColor(color);
			SolidPlane(center, rotation, size);
			WirePlane(center, rotation, size);
			ArrowRelativeSizeHead(center, center + (float3)(rotation * Vector3.up) * 0.5f, (float3)(rotation * Vector3.forward), 0.2f);
			PopColor();
		}
		/// <summary>\copydoc SolidBox(float3,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void SolidBox (float3 center, float3 size, Color color) {
			Reserve<Color32, BoxData>();
			Add(Command.Box | Command.PushColorInline);
			Add((Color32)color);
			Add(new BoxData { center = center, size = size });
		}

		/// <summary>\copydoc SolidBox(Bounds)</summary>
		/// <param name="color">Color of the object</param>
		public void SolidBox (Bounds bounds, Color color) {
			SolidBox(bounds.center, bounds.size, color);
		}

		/// <summary>\copydoc SolidBox(float3,Quaternion,float3)</summary>
		/// <param name="color">Color of the object</param>
		public void SolidBox (float3 center, Quaternion rotation, float3 size, Color color) {
			PushColor(color);
			using (WithMatrix(Matrix4x4.TRS(center, rotation, size))) {
				SolidBox(new Vector3(0.5f, 0.5f, 0.5f), Vector3.one);
			}
			PopColor();
		}

		/// <summary>\copydoc Label2D(float3,string,float)</summary>
		/// <param name="color">Color of the object</param>
		public void Label2D (float3 position, string text, float sizeInPixels, Color color) {
			Label2D(position, text, sizeInPixels, LabelAlignment.MiddleLeft, color);
		}
		/// <summary>\copydoc Label2D(float3,string,float)</summary>
		/// <param name="color">Color of the object</param>
		public void Label2D (float3 position, string text, Color color) {
			Label2D(position, text, 14, color);
		}
		/// <summary>\copydoc Label2D(float3,string,float,LabelAlignment)</summary>
		/// <param name="color">Color of the object</param>
		public void Label2D (float3 position, string text, float sizeInPixels, LabelAlignment alignment, Color color) {
			AssertBufferExists();
			var g = gizmos.Target as DrawingData;
			Reserve<Color32, TextData>();
			Add(Command.Text | Command.PushColorInline);
			Add((Color32)color);
			Add(new TextData { center = position, numCharacters = text.Length, sizeInPixels = sizeInPixels, alignment = alignment });

			Reserve(UnsafeUtility.SizeOf<System.UInt16>() * text.Length);
			for (int i = 0; i < text.Length; i++) {
				char c = text[i];
				System.UInt16 index = (System.UInt16)g.fontData.GetIndex(c);
				Add(index);
			}
		}
	}
}
